### ISSUE TITLE
プロジェクト詳細ページの実装

### ISSUE THREAD

**Issue by kugue99A** [NUTFes/NUTMEG-Seeds#15]

**Comment by YushiroDodo63** [comment]
- 画面左側は画像用にスペースを確保。
- Iconは[ここ](https://icon-icons.com/ja/%E6%A4%9C%E7%B4%A2/%E3%82%A2%E3%82%A4%E3%82%B3%E3%83%B3/?filtro=slack)を使う。
- Skills、MembersはAPIから取れるようにしてないから手書きで作成する
  - ここは配列で宣言する。
  - 配列に名前とかを宣言しといて、それをmapで回す
- 戻るボタンはhistory-backを使う
  - Next routerの機能
  - onClickに router.backをアロー関数で書く
- 戻るボタン
  - Negative-merginでカードにボタンを重ねて配置する
