### ISSUE TITLE
テーブルデータのリアクティブ化

### ISSUE THREAD

**Issue by kugue99A** [NUTFes/NUTMEG-Seeds#67]

**Comment by kugue99A** [comment]
詳細な実装方法は2022.4.2 14:00~にペアプロで説明

**Comment by YushiroDodo63** [comment]
変更するファイル
- UserPeojectAddModal
- UserSkillAddModal
- UserRecordAddModal
- PeojectAddModal
- PeojectUserAddModal

1. modelsのrbファイルにリロード用の関数を作成
2. controllerにリロード用の関数を作成
3. routes.rb に新しいルーティング定義を作成
4. tsxファイルでsubmit関数を作成
